spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/webtoon
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show_sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update